cableonda_adminin:
    resource: "@CableondaAdmininBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

leydi:
    pattern:   /leydi
    defaults:  { _controller: CableondaAdmininBundle:Default:Index }


soap:
    pattern:   /soap
    defaults:  { _controller: CableondaAdmininBundle:Logsesiones:Index }
