parameters:
#    cableonda_adminin.example.class: Cableonda\AdmininBundle\Example

services:
#    cableonda_adminin.example:
#        class: %cableonda_adminin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
